// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicpGvd74LYPiYScSccDVxgqqOCAE3SOM',
    appId: '1:1071697669526:web:505f805eae714a6b1281b7',
    messagingSenderId: '1071697669526',
    projectId: 'auth02-acb3c',
    authDomain: 'auth02-acb3c.firebaseapp.com',
    storageBucket: 'auth02-acb3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkcMnflJTTrc1RC_Iz7sgSUrBV1U4mGqk',
    appId: '1:1071697669526:android:6e512223a97f8e2d1281b7',
    messagingSenderId: '1071697669526',
    projectId: 'auth02-acb3c',
    storageBucket: 'auth02-acb3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCNasB-mCncNWzN3J7FUwhz34ZMzkfqc',
    appId: '1:1071697669526:ios:2157a9fc9fd380e51281b7',
    messagingSenderId: '1071697669526',
    projectId: 'auth02-acb3c',
    storageBucket: 'auth02-acb3c.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCNasB-mCncNWzN3J7FUwhz34ZMzkfqc',
    appId: '1:1071697669526:ios:c6d6381449e596151281b7',
    messagingSenderId: '1071697669526',
    projectId: 'auth02-acb3c',
    storageBucket: 'auth02-acb3c.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
