// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2EQy9lc-IX41kCEpZLtscRvMhBYfgI4g',
    appId: '1:527685097434:web:f565c31481cee1f51392e3',
    messagingSenderId: '527685097434',
    projectId: 'auth-7b480',
    authDomain: 'auth-7b480.firebaseapp.com',
    storageBucket: 'auth-7b480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLS2UE6CqG0xrrxQOt6mcAQVd-DO6ROII',
    appId: '1:527685097434:android:f09497218481b7151392e3',
    messagingSenderId: '527685097434',
    projectId: 'auth-7b480',
    storageBucket: 'auth-7b480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5jkAfURqCIQRL98OiIOC2r-GfEISLPM',
    appId: '1:527685097434:ios:e9396f9d00069b0f1392e3',
    messagingSenderId: '527685097434',
    projectId: 'auth-7b480',
    storageBucket: 'auth-7b480.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5jkAfURqCIQRL98OiIOC2r-GfEISLPM',
    appId: '1:527685097434:ios:4a8ed5d3894a37471392e3',
    messagingSenderId: '527685097434',
    projectId: 'auth-7b480',
    storageBucket: 'auth-7b480.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
